// Embeds UI assets into src/generated/assets.js as plain JS string exports.
// Ported from green's scripts/build-assets.mjs UNCHANGED — chat's /s.js is
// the FULL concatenation (client + ambient + chatcrypto + chat), because the
// chat pages need the gate crypto and the room UI. This is the one worker
// whose /s.js keeps every script.
//
// JSON.stringify does the escaping — template literals are deliberately
// avoided because CSS/JS containing backticks or ${ would corrupt them.
//
// ASSET_VERSION is a hash of the assets' bytes. src/ui/layout.js appends it to
// /chat/s.css and /chat/s.js as ?v=..., so those fixed URLs can carry an
// immutable year-long cache safely: the URL changes whenever the content does.
//
// Determinism matters: dist/index.js is a Terraform input; any run-to-run
// variation surfaces as a perpetual plan diff. Same bytes in, same hash out.
import { build } from "esbuild";
import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const outdir = join(root, "dist");

const css = await readFile(join(root, "src/ui/style.css"), "utf8");

const clientJs = await readFile(join(root, "src/ui/client.js"), "utf8");
const ambientJs = await readFile(join(root, "src/ui/ambient.js"), "utf8");
// chatcrypto.js publishes window.talviGate and must precede chat.js, which
// calls into it. Both only touch it after DOMContentLoaded, so the order is
// belt-and-braces rather than load-bearing.
const chatCryptoJs = await readFile(join(root, "src/ui/chatcrypto.js"), "utf8");
const chatJs = await readFile(join(root, "src/ui/chat.js"), "utf8");
// The shared shell's blade retraction (same bytes as hub/relay).
const bladeClientJs = await readFile(join(root, "src/ui/blade-client.js"), "utf8");

// The quiet 3D backdrop is bundled (it imports three.js) into a self-booting
// IIFE and appended — the same pipeline as the relay (P2), so /chat reads
// like /talvi. It self-guards on <canvas id="backdrop">.
await build({
  entryPoints: [join(root, "src/ui/backdrop.js")],
  outfile: join(outdir, "backdrop-bundle.js"),
  bundle: true,
  format: "iife",
  platform: "browser",
  minify: true,
  legalComments: "none",
  target: ["es2020"],
  logLevel: "warning",
});
const backdropJs = await readFile(join(outdir, "backdrop-bundle.js"), "utf8");

const js =
  clientJs +
  "\n" +
  ambientJs +
  "\n" +
  chatCryptoJs +
  "\n" +
  chatJs +
  "\n" +
  bladeClientJs +
  "\n" +
  backdropJs +
  "\n";

const version = createHash("sha256")
  .update(css)
  .update("\x00")
  .update(js)
  .digest("hex")
  .slice(0, 12);

const out =
  "// GENERATED by scripts/build-assets.mjs — do not edit, do not commit.\n" +
  `export const STYLE_CSS = ${JSON.stringify(css)};\n` +
  `export const CLIENT_JS = ${JSON.stringify(js)};\n` +
  `export const ASSET_VERSION = ${JSON.stringify(version)};\n`;

await mkdir(join(root, "src/generated"), { recursive: true });
await writeFile(join(root, "src/generated/assets.js"), out);
console.log(
  `build-assets: src/generated/assets.js written ` +
    `(v=${version}, css ${css.length}B, js ${js.length}B)`,
);
