// Hub asset pipeline (A5). Same shape as the 3d site's scripts/build-assets.mjs
// — bundles the client (three.js + the scene modules + the blade logic) with
// esbuild, then embeds the CSS and the JS bundle as plain JS string exports so
// the worker serves them without a file read and without inlining anything in
// HTML (CSP default-src 'none': a security decision driving a build decision).
//
// JSON.stringify does the escaping — template literals are deliberately
// avoided because CSS/JS containing backticks or ${ would corrupt them.
//
// ASSET_VERSION is a hash of the two assets' bytes. The page appends it to
// /h.css and /h.js as ?v=..., which is what lets those fixed URLs carry an
// immutable year-long cache safely: the URL changes whenever the content does.
//
// Determinism matters here beyond tidiness: the built worker is a Terraform
// input, so any run-to-run variation surfaces as a perpetual plan diff. Same
// bytes in, same hash out — no clock, no randomness, no filesystem ordering.
import { build } from "esbuild";
import { createHash } from "node:crypto";
import { mkdir, readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const outdir = join(root, "dist");

// Bundle the client (three + scene + blade). Entry is src/ui/client.js.
await build({
  entryPoints: [join(root, "src/ui/client.js")],
  outfile: join(outdir, "client-bundle.js"),
  bundle: true,
  format: "iife",
  platform: "browser",
  minify: true,
  legalComments: "none",
  target: ["es2020"],
  logLevel: "warning",
});

const js = await readFile(join(outdir, "client-bundle.js"), "utf8");
const css = await readFile(join(root, "src/ui/style.css"), "utf8");

const GLYPHS = ["\u25A3", "\u25A4", "\u25C8", "\u25C6"];
if (js.includes("\uFFFD") || js.includes("\\uFFFD")) {
  throw new Error("build-assets: U+FFFD in bundled worker — glyph encoding lost");
}
for (const srcName of ["src/scene/world.js", "src/ui/hubpage.js"]) {
  const src = await readFile(join(root, srcName), "utf8");
  if (src.includes("\uFFFD")) {
    throw new Error(`build-assets: U+FFFD in ${srcName} — restore cube glyphs`);
  }
  for (const g of GLYPHS) {
    if (!src.includes(g)) {
      const cp = g.codePointAt(0).toString(16).toUpperCase();
      throw new Error(`build-assets: missing cube glyph U+${cp} in ${srcName}`);
    }
  }
}
for (const g of GLYPHS) {
  const cp = g.codePointAt(0).toString(16).toUpperCase();
  if (!js.includes(g) && !js.includes("\\u" + cp)) {
    throw new Error(`build-assets: missing cube glyph U+${cp} in bundled worker`);
  }
}

const CANONICAL = "v9.0";
const HEADER_VER = /^(?:\/\/|\/\*).*\((v\d+\.\d+)\)/;
const STALE_VER = /\(v(?:4\.1|8\.0)\)/;
for (const dir of ["src/scene", "src/ui"]) {
  const names = await readdir(join(root, dir), { recursive: true });
  for (const name of names) {
    if (!/\.(js|css)$/.test(name)) continue;
    const rel = `${dir}/${name}`;
    const src = await readFile(join(root, rel), "utf8");
    const hm = src.split("\n", 1)[0].match(HEADER_VER);
    if (hm && hm[1] !== CANONICAL) {
      throw new Error(`build-assets: ${rel} header is ${hm[1]}, want ${CANONICAL}`);
    }
    if (STALE_VER.test(src)) {
      throw new Error(`build-assets: stale version stamp in ${rel} (want ${CANONICAL})`);
    }
  }
}

const version = createHash("sha256")
  .update(css)
  .update("\x00")
  .update(js)
  .digest("hex")
  .slice(0, 12);

const out =
  "// GENERATED by scripts/build-assets.mjs — do not edit, do not commit.\n" +
  `export const H_CSS = ${JSON.stringify(css)};\n` +
  `export const H_JS = ${JSON.stringify(js)};\n` +
  `export const ASSET_VERSION = ${JSON.stringify(version)};\n`;

await mkdir(join(root, "src/generated"), { recursive: true });
await writeFile(join(root, "src/generated/assets.js"), out);
console.log(
  `build-assets: client ${js.length}B, css ${css.length}B, ` +
    `v=${version}, total worker payload ~${(js.length + css.length) / 1024 | 0} KiB raw`,
);
