// Learn asset pipeline (PR2 + PR5). Same shape as the hub/relay
// scripts/build-assets.mjs — embeds the learn /s.css, /s.js and the
// curriculum JSON as plain JS string exports so the worker serves them
// without a file read and without inlining anything in HTML (CSP
// default-src 'none': a security decision driving a build decision).
//
// Curriculum is code (decision 4): content lives in learn/curriculum/*.json,
// is validated by scripts/content-lint.mjs (a citation-less exercise fails
// the build), and rides in the bundle here. Never a database.
//
// JSON.stringify does the escaping — template literals are deliberately
// avoided because CSS/JS containing backticks or ${ would corrupt them.
//
// ASSET_VERSION is a hash of the assets' bytes. PR6's UI appends it to
// /s.css and /s.js as ?v=..., which is what lets those fixed URLs carry an
// immutable year-long cache safely: the URL changes whenever the content does.
// Curriculum bytes feed the same hash, so a curriculum change busts the cache.
//
// Determinism matters here beyond tidiness: dist/index.js is a Terraform
// input, so any run-to-run variation surfaces as a perpetual plan diff. Same
// bytes in, same hash out — no clock, no randomness, no filesystem ordering.
// readdir order is sorted before hashing/embedding.
import { createHash } from "node:crypto";
import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const css = await readFile(join(root, "src/ui/style.css"), "utf8");
const js = await readFile(join(root, "src/ui/client.js"), "utf8");

// Curriculum: read every unit JSON in sorted filename order and embed them as
// one array, so the path graph is derivable from the bundle alone. The
// content-lint has already run (wired ahead of this step in npm run build).
const curriculumFiles = (await readdir(join(root, "curriculum")))
  .filter((f) => f.endsWith(".json"))
  .sort();
const units = [];
for (const file of curriculumFiles) {
  units.push(JSON.parse(await readFile(join(root, "curriculum", file), "utf8")));
}

const version = createHash("sha256")
  .update(css)
  .update("\x00")
  .update(js)
  .update("\x00")
  .update(JSON.stringify(units))
  .digest("hex")
  .slice(0, 12);

const out =
  "// GENERATED by scripts/build-assets.mjs — do not edit, do not commit.\n" +
  `export const STYLE_CSS = ${JSON.stringify(css)};\n` +
  `export const CLIENT_JS = ${JSON.stringify(js)};\n` +
  `export const CURRICULUM = ${JSON.stringify(units)};\n` +
  `export const ASSET_VERSION = ${JSON.stringify(version)};\n`;

await mkdir(join(root, "src/generated"), { recursive: true });
await writeFile(join(root, "src/generated/assets.js"), out);
console.log(
  `build-assets: src/generated/assets.js written ` +
    `(v=${version}, css ${css.length}B, js ${js.length}B, curriculum ${units.length} unit(s))`,
);
