// Embeds UI assets into src/generated/assets.js as plain JS string exports.
// JSON.stringify does the escaping — template literals are deliberately
// avoided because CSS/HTML containing backticks or ${ would corrupt them.
// Step 2 only proves this pipeline works; real assets arrive in Step 5.
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const css = await readFile(join(root, "src/ui/style.css"), "utf8");

const out =
  "// GENERATED by scripts/build-assets.mjs — do not edit, do not commit.\n" +
  `export const STYLE_CSS = ${JSON.stringify(css)};\n`;

await mkdir(join(root, "src/generated"), { recursive: true });
await writeFile(join(root, "src/generated/assets.js"), out);
console.log("build-assets: src/generated/assets.js written");
