// Embeds UI assets into src/generated/assets.js as plain JS string exports.
// JSON.stringify does the escaping — template literals are deliberately
// avoided because CSS/JS containing backticks or ${ would corrupt them.
// Step 2 proved the pipeline; Step 5 fills it with the real assets and adds
// the content hash.
//
// ASSET_VERSION is a hash of the two assets' bytes. src/ui/layout.js appends
// it to /s.css and /s.js as ?v=..., which is what lets those fixed URLs carry
// an immutable year-long cache safely: the URL changes whenever the content
// does. Without it, the first CSS edit after Step 5 would stay invisible for a
// year to anyone who had already loaded a page.
//
// Determinism matters here beyond tidiness: dist/index.js is a Terraform
// input, so any run-to-run variation surfaces as a perpetual plan diff (see
// 03-lessons-learned §3). Same bytes in, same hash out — no clock, no
// randomness, no filesystem ordering.
import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const css = await readFile(join(root, "src/ui/style.css"), "utf8");
// /s.js is a CONCATENATION, not a bundle: these are plain browser scripts,
// each self-booting and sharing nothing. Concatenating keeps them separately
// readable and lintable without introducing a module loader for two files.
// The sprite is a real PNG authored outside this repo (generated in a pixel
// tool, white keyed out and downscaled with ffmpeg). Embedded as base64 and
// served from the Worker at /s.png — no external request, and `img-src 'self'`
// already covers it, so the CSP does not move.
const spritePng = await readFile(join(root, "src/ui/sprites/figure.png"));
const spriteB64 = spritePng.toString("base64");

const clientJs = await readFile(join(root, "src/ui/client.js"), "utf8");
const ambientJs = await readFile(join(root, "src/ui/ambient.js"), "utf8");
// chatcrypto.js publishes window.talviGate and must precede chat.js, which
// calls into it. Both only touch it after DOMContentLoaded, so the order is
// belt-and-braces rather than load-bearing — but a reader should not have to
// work that out, and a future top-level call would break silently otherwise.
const chatCryptoJs = await readFile(join(root, "src/ui/chatcrypto.js"), "utf8");
const chatJs = await readFile(join(root, "src/ui/chat.js"), "utf8");
const js = clientJs + "\n" + ambientJs + "\n" + chatCryptoJs + "\n" + chatJs;

const version = createHash("sha256")
  .update(css)
  .update("\x00")
  .update(js)
  .digest("hex")
  .slice(0, 12);

const out =
  "// GENERATED by scripts/build-assets.mjs — do not edit, do not commit.\n" +
  `export const STYLE_CSS = ${JSON.stringify(css)};\n` +
  `export const CLIENT_JS = ${JSON.stringify(js)};\n` +
  `export const ASSET_VERSION = ${JSON.stringify(version)};\n` +
  `export const SPRITE_PNG_B64 = ${JSON.stringify(spriteB64)};\n`;

await mkdir(join(root, "src/generated"), { recursive: true });
await writeFile(join(root, "src/generated/assets.js"), out);
console.log(
  `build-assets: src/generated/assets.js written ` +
    `(v=${version}, css ${css.length}B, js ${js.length}B)`,
);
