// Embeds UI assets into src/generated/assets.js as plain JS string exports.
// Ported from green's scripts/build-assets.mjs, with chat REMOVED: the relay
// (app.*/relay) is the file-drop only — chat stays on green until Workstream C.
//
// JSON.stringify does the escaping — template literals are deliberately
// avoided because CSS/JS containing backticks or ${ would corrupt them.
//
// ASSET_VERSION is a hash of the assets' bytes. src/ui/layout.js appends it to
// /relay/s.css and /relay/s.js as ?v=..., which is what lets those fixed URLs
// carry an immutable year-long cache safely: the URL changes whenever the
// content does.
//
// Determinism matters here beyond tidiness: dist/index.js is a Terraform
// input, so any run-to-run variation surfaces as a perpetual plan diff. Same
// bytes in, same hash out — no clock, no randomness, no filesystem ordering.
import { createHash } from "node:crypto";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

const css = await readFile(join(root, "src/ui/style.css"), "utf8");
const spritePng = await readFile(join(root, "src/ui/sprites/figure.png"));
const spriteB64 = spritePng.toString("base64");

// /s.js is a CONCATENATION, not a bundle: these are plain browser scripts,
// each self-booting and sharing nothing. The relay serves client.js (upload +
// view behaviour) + ambient.js (the drifting pad) + chatcrypto.js (the
// download-PIN gate derivation, Workstream E — same KDF chat uses, moved
// byte-identical). NO chat UI scripts.
const clientJs = await readFile(join(root, "src/ui/client.js"), "utf8");
const ambientJs = await readFile(join(root, "src/ui/ambient.js"), "utf8");
const chatCryptoJs = await readFile(join(root, "src/ui/chatcrypto.js"), "utf8");
// The shared shell's blade retraction (same bytes as hub/chat).
const bladeClientJs = await readFile(join(root, "src/ui/blade-client.js"), "utf8");
const js = clientJs + "\n" + ambientJs + "\n" + chatCryptoJs + "\n" + bladeClientJs + "\n";

const version = createHash("sha256")
  .update(css)
  .update("\x00")
  .update(js)
  .digest("hex")
  .slice(0, 12);

const out =
  "// GENERATED by scripts/build-assets.mjs — do not edit, do not commit.\n" +
  `export const STYLE_CSS = ${JSON.stringify(css)};\n` +
  `export const CLIENT_JS = ${JSON.stringify(js)};\n` +
  `export const ASSET_VERSION = ${JSON.stringify(version)};\n` +
  `export const SPRITE_PNG_B64 = ${JSON.stringify(spriteB64)};\n`;

await mkdir(join(root, "src/generated"), { recursive: true });
await writeFile(join(root, "src/generated/assets.js"), out);
console.log(
  `build-assets: src/generated/assets.js written ` +
    `(v=${version}, css ${css.length}B, js ${js.length}B)`,
);
